server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:
  datasource:
    url: ${RDS_ENDPOINT}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
  aop:
    proxy-target-class: false

security:
  refresh:
    expiration: 3600000
  jwt:
    key: ${JWT_KEY}
    expiration:
      access: 2628000000
cloud:
  aws:
    credentials:
      accessKey: ${S3_KEY}
      secretKey: ${S3_SECRET_KEY}
    s3:
      bucket: "woohaengshi-s3"
    region:
      static: ap-northeast-2
    stack:
      auto: false

woohaengshi:
  openapi:
    dev-url: "http://localhost:8080"
    prod-url: "https://api.myapp.com"